site_name: Desafío UPEIM
site_url: https://bloodsharp.github.io/UPEIM/
nav:
  - Inicio: index.md
  - Backend: backend.md
  - Base de datos: database.md
  - Frontend: frontend.md
  - Documentación de esta página: documentation.md
theme: readthedocs
